export function getTitleFromID(titleId: string) {
  return titles.find( title => title.id === titleId).en
}

export const titles = [
  { id: 'TitleData_Abandoned', en: "Abandoned" },
  { id: 'TitleData_Aesop', en: "Aesop" },
  { id: 'TitleData_AllStar', en: "All-Star" },
  { id: 'TitleData_AmongTheStars', en: "Among the Stars" },
  { id: 'TitleData_AngelicSupportMastery', en: "Time Traveler" },
  { id: 'TitleData_AscendingChampion', en: "Ascending Champion" },
  { id: 'TitleData_BackpassBeast', en: "Backpass Beast" },
  { id: 'TitleData_BestintheWest', en: "Best in the West" },
  { id: 'TitleData_BetaReward', en: "The Eternal Flame" },
  { id: 'TitleData_BlobWhisperer', en: "Blob Whisperer" },
  { id: 'TitleData_Bomba', en: "Bomba!" },
  { id: 'TitleData_BPS1Investor', en: "The Early Investor" },
  { id: 'TitleData_BPS1Striker', en: "Beta Season Striker" },
  { id: 'TitleData_BPS2Hotshot', en: "The Hotshot" },
  { id: 'TitleData_BPS2Striker', en: "Season Two Striker" },
  { id: 'TitleData_BravedtheTank', en: "Braved the Tank" },
  { id: 'TitleData_BuiltDifferent', en: "Built Different" },
  { id: 'TitleData_Caughtin4k', en: "Caught in 4k" },
  { id: 'TitleData_CCLChampion', en: "CCL Champion" },
  { id: 'TitleData_CCLFinalist', en: "CCL Finalist" },
  { id: 'TitleData_CCLQualifier', en: "CCL Qualifier" },
  { id: 'TitleData_CCLTop8', en: "CCL Top 8" },
  { id: 'TitleData_ChaoticRocketeerMastery', en: "Chaotic" },
  { id: 'TitleData_Chatter', en: "Chatter" },
  { id: 'TitleData_ClarionCorpVS', en: "Test Subject" },
  { id: 'TitleData_CleverSummonerMastery', en: "Blobbo Buddy" },
  { id: 'TitleData_Clipmaster', en: "Clipmaster" },
  { id: 'TitleData_Comfy', en: "Comfy" },
  { id: 'TitleData_Competitor', en: "Competitor" },
  { id: 'TitleData_Connoisseur', en: "Connoisseur" },
  { id: 'TitleData_Contributor', en: "Contributor" },
  { id: 'TitleData_CoveredinPaint', en: "Covered in Paint" },
  { id: 'TitleData_Cracked', en: "Cracked" },
  { id: 'TitleData_CreamOfTheCrop', en: "Cream of the Crop" },
  { id: 'TitleData_Cringe', en: "Cringe" },
  { id: 'TitleData_CrustaceanConnoisseur', en: "Crustacean Connoisseur" },
  { id: 'TitleData_DeepEnd', en: "Deep End" },
  { id: 'TitleData_Deity', en: "Deity" },
  { id: 'TitleData_DemonQueuer', en: "Demon Queuer" },
  { id: 'TitleData_DoubleCringe', en: "Double Cringe" },
  { id: 'TitleData_DrumOniMastery', en: "Taiko Trailblazer" },
  { id: 'TitleData_EDMOniMastery', en: "Virtuoso" },
  { id: 'TitleData_EmpoweringEnchanterMastery', en: "Bewitched" },
  { id: 'TitleData_EuroSage', en: "Euro Sage" },
  { id: 'TitleData_FarewellBanner', en: "Promethean" },
  { id: 'TitleData_FlashySwordsmanMastery', en: "Blade Master" },
  { id: 'TitleData_FlexibleBrawlerMastery', en: "Rising Star" },
  { id: 'TitleData_FloppianFinalist', en: "Floppian Finalist" },
  { id: 'TitleData_Founder', en: "Founding Member" },
  { id: 'TitleData_GlitchCatShock', en: "Glitch Cat Shock!" },
  { id: 'TitleData_GraduatingClass', en: "Graduating Class" },
  { id: 'TitleData_GravityMageMastery', en: "Illusionist" },
  { id: 'TitleData_HalfBaked', en: "Half-Baked" },
  { id: 'TitleData_HallofFame', en: "Hall of Fame" },
  { id: 'TitleData_Halloween_Pumpkin', en: "Pumpkin" },
  { id: 'TitleData_Halloween_Spooky', en: "Spooky" },
  { id: 'TitleData_HealerMastery', en: "Nao or Never" },
  { id: 'TitleData_HulkingBeastMastery', en: "Excessive" },
  { id: 'TitleData_HyperX', en: "HyperX Hero" },
  { id: 'TitleData_IceCreamEnjoyer', en: "Ice Cream Enjoyer" },
  { id: 'TitleData_Idol', en: "Idol" },
  { id: 'TitleData_Irrefutable', en: "Irrefutable" },
  { id: 'TitleData_KazAngler', en: "Kaz Angler" },
  { id: 'TitleData_Knower', en: "Knower" },
  { id: 'TitleData_KnowledgeGapped', en: "Knowledge Gapped" },
  { id: 'TitleData_KOChamp', en: "K.O. Champ" },
  { id: 'TitleData_LateNightLobster', en: "Late Night Lobster" },
  { id: 'TitleData_LivesbytheBrush', en: "Lives by the Brush" },
  { id: 'TitleData_LivingCalculator', en: "Living Calculator" },
  { id: 'TitleData_LANimal', en: "LANimal" },
  { id: 'TitleData_MagicalPlaymakerMastery', en: "Glitchy" },
  { id: 'TitleData_ManipulatingMastermindMastery', en: "Sinister Shadow" },
  { id: 'TitleData_MasterBrawler', en: "Expert Brawler" },
  { id: 'TitleData_MasterSniper', en: "Expert Sniper" },
  { id: 'TitleData_MeteoricRise', en: "Meteoric Rise" },
  { id: 'TitleData_MidfieldMafia', en: "Midfield Mafia" },
  { id: 'TitleData_MostDangerousGame', en: "Most Dangerous Game" },
  { id: 'TitleData_MovieStar', en: "Movie Star" },
  { id: 'TitleData_NimbleBlasterMastery', en: "Space Invader" },
  { id: 'TitleData_Nocturnal', en: "Nocturnal" },
  { id: 'TitleData_None', en: "No title :(" },
  { id: 'TitleData_o7', en: "o7" },
  { id: 'TitleData_OniRelease', en: "Drum Breaker" },
  { id: 'TitleData_OrbGobbler', en: "Orb Enjoyer" },
  { id: 'TitleData_OutforLunch', en: "Out for Lunch" },
  { id: 'TitleData_OwnGoaler', en: "Own Goaler" },
  { id: 'TitleData_PBWM', en: "PBWM" },
  { id: 'TitleData_Performer', en: "Performer" },
  { id: 'TitleData_Picasso', en: "Picasso" },
  { id: 'TitleData_PixelArtist', en: "Pixel Artist" },
  { id: 'TitleData_ProcurestheRock', en: "Core Controller" },
  { id: 'TitleData_ProGamer', en: "Pro Gamer" },
  { id: 'TitleData_ProLeagueVS', en: "Finalist" },
  { id: 'TitleData_ProYapper', en: "Pro Yapper" },
  { id: 'TitleData_RAAAHHHHHH', en: "RAAAHHHHHH" },
  { id: 'TitleData_ReadyForLiftoff', en: "Ready for Liftoff" },
  { id: 'TitleData_RiseandGrind', en: "Rise & Grind" },
  { id: 'TitleData_RisenAbove', en: "Risen Above" },
  { id: 'TitleData_RockOniMastery', en: "Rock Star" },
  { id: 'TitleData_S1Champion', en: "Beta Season Omega Striker" },
  { id: 'TitleData_S1TournamentChampion', en: "S1 Tournament Champion" },
  { id: 'TitleData_S1TournamentFlawless', en: "S1 Flawless Tournament Winner" },
  { id: 'TitleData_S1TournamentLegend', en: "S1 Tournament Legend" },
  { id: 'TitleData_S1TournamentWarrior', en: "S1 Tournament Warrior" },
  { id: 'TitleData_S1TournamentWinner', en: "S1 Tournament Winner" },
  { id: 'TitleData_S2Champion', en: "Season One Omega Striker" },
  { id: 'TitleData_S2TournamentParticipant', en: "Ignited" },
  { id: 'TitleData_ScalingForLateGame', en: "Scaling For Late Game" },
  { id: 'TitleData_SeraStar', en: "SeraStar" },
  { id: 'TitleData_ShieldUserMastery', en: "Unbreakable" },
  { id: 'TitleData_ShinyGoldenMedal', en: "Shiny Golden Medal" },
  { id: 'TitleData_SigmaStriker', en: "Sigma Striker" },
  { id: 'TitleData_SitDownLilBro', en: "Sit Down Lil' Bro" },
  { id: 'TitleData_SkystheLimit', en: "Sky's the Limit" },
  { id: 'TitleData_SpecializedTrainer', en: "Specialized Trainer" },
  { id: 'TitleData_SpeedySkirmisherMastery', en: "Prodigy" },
  { id: 'TitleData_StalwartProtectorMastery', en: "The Most Huggable" },
  { id: 'TitleData_Stargazer', en: "Stargazer" },
  { id: 'TitleData_Striker', en: "The Eager Rookie" },
  { id: 'TitleData_StudiestheBlade', en: "Studies the Blade" },
  { id: 'TitleData_Summer_ExtremelyPunny', en: "Extremely Punny" },
  { id: 'TitleData_Summer_HotandBothered', en: "Hot and Bothered" },
  { id: 'TitleData_Summer_LifeoftheParty', en: "Life of the Party" },
  { id: 'TitleData_Summer_OmegaSpiker', en: "Omega Spiker" },
  { id: 'TitleData_Summer_OnDuty', en: "On Duty" },
  { id: 'TitleData_Summer_SeaTier', en: "Sea Tier" },
  { id: 'TitleData_Summer_SweetTreat', en: "Sweet Treat" },
  { id: 'TitleData_SurfsUp', en: "Surf's Up!" },
  { id: 'TitleData_TeamEDMOni', en: "Thousand Absolutes" },
  { id: 'TitleData_TeamRockOni', en: "Vice Versa" },
  { id: 'TitleData_TeaTime_Boba', en: "Boba" },
  { id: 'TitleData_TeaTime_Caffeinated', en: "Caffeinated" },
  { id: 'TitleData_TeaTime_Jelly', en: "Jelly" },
  { id: 'TitleData_TempoSniperMastery', en: "Fashion Icon" },
  { id: 'TitleData_TheChampion', en: "The Champion" },
  { id: 'TitleData_TheDirector', en: "The Director" },
  { id: 'TitleData_TheGlizzard', en: "The Glizzard" },
  { id: 'TitleData_TheGoldenStandard', en: "The Golden Standard" },
  { id: 'TitleData_TheNextBigThing', en: "The Next Big Thing" },
  { id: 'TitleData_TheProphet', en: "The Prophet" },
  { id: 'TitleData_TheShepherd', en: "The Shepherd" },
  { id: 'TitleData_TournamentShadowHelper', en: "Shadow Helper" },
  { id: 'TitleData_TournamentShadowHero', en: "Shadow Hero" },
  { id: 'TitleData_TournamentShadowLoser', en: "World's Best Loser" },
  { id: 'TitleData_TournamentShadowSelfless', en: "The Selfless" },
  { id: 'TitleData_TournamentShadowWarrior', en: "Shadow Warrior" },
  { id: 'TitleData_Trailblazer', en: "Trailblazer" },
  { id: 'TitleData_UmbrellaUserMastery', en: "Loose Cannon" },
  { id: 'TitleData_WatchingTheSunset', en: "Watching The Sunset" },
  { id: 'TitleData_WestieRoyalty', en: "Westie Royalty" },
  { id: 'TitleData_Whatdayisit', en: "What day is it?" },
  { id: 'TitleData_WhipFighterMastery', en: "Off the Hook" },
]