// Self-Contained Script designed for setting up or updating tedious database entries.

import { Awakenings } from '../prisma/client';
import { prisma } from './plugins/prisma';
import chalk from "chalk";

async function main() {
  console.log(chalk.greenBright(`[>] Running setup script...`));

  await setupAwakenings();
  await setupStrikers();

  console.log(chalk.greenBright(`[>] Setup Complete.`));
  return 0;
}


async function setupAwakenings() {
  const awakenings = [
    { id: 'T_Aerials', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_Aerials.webp`, name: `Aerials`, description: `DASH range, BLINK range, and HASTE effects increased +75%. PROJECTILES gain +42.5% travel or cast range.` },
    { id: 'T_AmongTitans', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_AmongTitans.webp`, name: `Among Titans`, description: `Lose 30% Size and gain +12% Speed. Additionally, your teammates gain +15% Size.` },
    { id: 'T_BigFish', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_BigFish.webp`, name: `Big Fish`, description: `Gain +22.5% Size and +175 max stagger.` },
    { id: 'T_BuiltDifferent', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_BuiltDifferent.webp`, name: `Built Different`, description: `Gain +22.5% Size. Your IMPACT abilities hit +5% harder. (+1% on Core).` },
    { id: 'T_BulkUp', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_BulkUp.webp`, name: `Bulk Up`, description: `Gain +300 max stagger. Gain an additional +1.5 Power for every 100 max stagger you have.` },
    { id: 'T_CastToLast', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_CastToLast.webp`, name: `Cast To Last`, description: `Ability BUFFS and DEBUFFS you cast last +55% longer. CREATIONS last +40% longer.` },
    { id: 'T_Catalyst', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_Catalyst.webp`, name: `Catalyst`, description: `Gain +15% more Energy from dealing damage. Taking damage generates +3.6 Energy. (+1.2 for LIGHT hits).` },
    { id: 'T_Chronoboost', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_Chronoboost.webp`, name: `Chronoboost`, description: `DASH range, BLINK range, and HASTE effects increased +75%. Ability BUFFS and DEBUFFS last +22.5% longer.` },
    { id: 'T_DeadEye', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_DeadEye.webp`, name: `Deadeye`, description: `Attack +25% harder (+6.5% to Core) against targets at 525+ range.` },
    { id: 'T_Demolitionist', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_Demolitionist.webp`, name: `Demolitionist`, description: `Gain +20% Size. Whenever you destroy or assist in destroying an enemy barrier, all your cooldowns are reduced by 3s.` },
    { id: 'T_Egoist', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_Egoist.webp`, name: `Egoist`, description: `Evades refund 8 Energy (16 from Energy Bursts). Reaching max Energy grants +60% Speed for 6s, reducing to +8% speed when you remain at max Energy.` },
    { id: 'T_ExplosiveEntrance', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_ExplosiveEntrance.webp`, name: `Explosive Entrance`, description: `DASH range, BLINK range, and HASTE effects/range increased +70%. Your IMPACT abilities hit +15% harder. (+3.25% on Core)` },
    { id: 'T_ExtraSpecial', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_ExtraSpecial.webp`, name: `Extra Special`, description: `SPECIAL cooldown reduced by -25%. Each round, its cooldown is reset.` },
    { id: 'T_FightOrFlight', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_FightOrFlight.webp`, name: `Fight Or Flight`, description: `Gain +12.5% Speed for 1.25s whenever you hit something or get hit. Refresh your SECONDARY whenever you stagger an enemy or become staggered.` },
    { id: 'T_FireUp', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_FireUp.webp`, name: `Fire Up`, description: `Gain 10 Energy on round start. Casting Energy Burst restores 25% of max Energy to other allies and Speeds up your whole team by 40% for 5s.` },
    { id: 'T_GlassCannon', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_GlassCannon.webp`, name: `Glass Cannon`, description: `Gain +4 Power and +2% Speed every 2s. (up to +28 Power and +14% Speed). Getting hit resets the timer.` },
    { id: 'T_HotShot', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_HotShot.webp`, name: `Hotshot`, description: `Abilities hit the Core +13% harder and refund 32.5% of the ability's cooldown on hit. Applies once per cast, refunding a max of 3s.` },
    { id: 'T_ImpactSpecialist', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_ImpactSpecialist.webp`, name: `Specialized Training`, description: `SPECIAL hits +35% harder (+8% to Core) and healing is +40% more effective.` },
    { id: 'T_MissilePropulsion', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_MissilePropulsion.webp`, name: `Missile Propulsion`, description: `PROJECTILES gain +70% travel or cast range and hit +22.5% harder (+4.5% to Core).` },
    { id: 'T_MomentumBoots', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_MomentumBoots.webp`, name: `Momentum Boots`, description: `` },
    { id: 'T_Monumentalist', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_Monumentalist.webp`, name: `Monumentalist`, description: `CREATIONS gain +85% size and hit +20% harder. (+4% to Core)` },
    { id: 'T_OneTwoPunch', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_OneTwoPunch.webp`, name: `One-Two Punch`, description: `Attack +20% harder (+12% to CORE) against targets you've hit within 1.5s.` },
    { id: 'T_OrbSharer', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_OrbSharer.webp`, name: `Orb Replicator`, description: `110% of benefits from Power Orbs you collect is also granted to allies. (..Yes, your allies get more than you do...)` },
    { id: 'T_PeakPerformance', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_PeakPerformance.webp`, name: `Peak Performance`, description: `Gain +300 max stagger. Gain an additional +0.50% Speed for every 100 max stagger you have.` },
    { id: 'T_PerfectForm', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_PerfectForm.webp`, name: `Perfect Form`, description: `Hits reduce other ability cooldowns by -12%, up to 1.5s per hit (-4%/0.5s for LIGHT hits).` },
    { id: 'T_PrimeTime', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_PrimeTime.webp`, name: `Primetime`, description: `PRIMARY gains +1 charge and hits 4.5% weaker. (-1% to the Core)` },
    { id: 'T_PrizeFighter', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_PrizeFighter.webp`, name: `Prize Fighter`, description: `Begin each set with 1 Prize Fighter stack, granting +18 Power. Takedowns grant +1 Prize Fighter stack (max 4 stacks). Getting K.O.'d removes a stack. Stacks reset between sets.` },
    { id: 'T_QuickStrike', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_QuickStrike.webp`, name: `Quick Strike`, description: `STRIKE cooldown reduced by -15%. STRIKE hits grant +2 additional energy.` },
    { id: 'T_RapidFire', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_RapidFire.webp`, name: `Rapid Fire`, description: `PRIMARY cooldown reduced by -33%.` },
    { id: 'T_Reverberation', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_Reverberation.webp`, name: `Reverberation`, description: `Gain +360 max stagger. Gain an additional +1.20 Cooldown Rate for every 100 max stagger you have.` },
    { id: 'T_ShockAndAwe', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_ShockAndAwe.webp`, name: `Heavy Impact`, description: `IMPACTS hit +15% harder (+4% on Core). Whenever you attack 2 or more targets with a single ability, its cooldown is reduced by -22.5% (up to 3s).` },
    { id: 'T_SiegeMachine', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_SiegeMachine.webp`, name: `Siege Machine`, description: `PROJECTILES gain +30% travel or cast range. CREATIONS gain +30% duration and hit +20% harder. (+4% to Core)` },
    { id: 'T_SparkofAgility', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_SparkofAgility.webp`, name: `Spark of Agility`, description: `Grants +1 SPARK. Gain +2% Speed, plus +5% per SPARK you have.` },
    { id: 'T_SparkofFocus', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_SparkofFocus.webp`, name: `Spark of Focus`, description: `Grants +1 SPARK. Gain +5 Cooldown Rate, additionally +9 per SPARK you have.` },
    { id: 'T_SparkofLeadership', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_SparkofLeadership.webp`, name: `Spark of Leadership`, description: `Grants +1 SPARK. Your teammates gain 25% of your SPARK effects. Additionally, you gain +6 Cooldown Rate, +130 stagger, +8 Power, and +2% speed.` },
    { id: 'T_SparkofResilience', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_SparkofResilience.webp`, name: `Spark of Resilience`, description: `Grants +1 SPARK. Gain +105 max stagger, additionally +350 per SPARK you have.` },
    { id: 'T_SparkofStrength', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_SparkofStrength.webp`, name: `Spark of Strength`, description: `Grants +1 SPARK. Gain +4 Power, additionally +18 per SPARK you have.` },
    { id: 'T_StaggerSwagger', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_StaggerSwagger.webp`, name: `Stagger Swagger`, description: `Gain +7% Speed. While below 50% stagger, this effect increases to +15% and you heal +150 HP/s, including while in the Staggered state.` },
    { id: 'T_SuperSurge', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_SuperSurge.webp`, name: `Super Surge`, description: `DASH range, BLINK range, and HASTE effects increased 75%. These abilities hit 25% harder (8% to Core).` },
    { id: 'T_TeamPlayer', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_TeamPlayer.webp`, name: `Team Player`, description: `STRIKE hits the core +15% harder when aiming towards a teammate. If that teammate STRIKES the core within 1.5s, they will hit the core +12.5% harder. If they too STRIKE towards another teammate, they can transfer this buff.` },
    { id: 'T_TempoSwings', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_TempoSwings.webp`, name: `Tempo Swing`, description: `Hitting anything heals you for 6% of your max Stagger (2% for LIGHT hits) and deals that amount as damage to the target hit.` },
    { id: 'T_TimelessCreator', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_TimelessCreator.webp`, name: `Timeless Creator`, description: `CREATIONS gain +60% duration and +35% size.` },
    { id: 'T_TwinDrive', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_TwinDrive.webp`, name: `Twin Drive`, description: `SECONDARY gains +1 charge and has a -2.5% decreased cooldown.` },
    { id: 'T_Unstoppable', image: `${process.env.CDN_BASE_URL ?? 'https://cdn.clarioncorp.net'}/awakening/T_Unstoppable.webp`, name: `Unstoppable`, description: `Gain a shield that protects you from 100% of the damage and 100% knockback from the first hit you take. The shield recharges at the start of each round and after 6.5s of not getting hit.` },
  ];

  for (const awakening of awakenings) {
    await prisma.awakenings.upsert({
      where: { id: awakening.id },
      update: {
        name: awakening.name,
        description: awakening.description,
        image: awakening.image,
      },
      create: {
        id: awakening.id,
        name: awakening.name,
        description: awakening.description,
        image: awakening.image,
        active: true, // Just make them all true by default and change later
      },
    });
    console.log(chalk.gray(`[DEBUG] Upserted ${awakening.id} to Awakenings Table!`));
  }

  console.log(chalk.greenBright(`[>] Successfully added all awakenings.`));
}

async function setupStrikers() {
  const strikers = [
    {
      id: "CD_MagicalPlaymaker",
      name: "Ai.Mi",
      color: "#f786a1",
      cost: 0,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_MagicalPlaymaker_Default.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_MagicalPlaymaker.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_MagicalPlaymaker.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_MagicalPlaymaker.png",
      description: "",
      baseStagger: 1200,
      regenRate: 8349,
      power: 100,
      speed: 450,
      size: 100,
    },
    {
      id: "CD_ShieldUser",
      name: "Asher",
      color: "#ff8247",
      cost: 30000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_ShieldUser.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_ShieldUser.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_ShieldUser.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_ShieldUser.png",
      description: "",
      baseStagger: 1400,
      regenRate: 8349,
      power: 125,
      speed: 440,
      size: 100,
    },
    {
      id: "CD_AngelicSupport",
      name: "Atlas",
      color: "#fff347",
      cost: 10000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_AngelicSupport.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_AngelicSupport.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_AngelicSupport.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_AngelicSupport.png",
      description: "",
      baseStagger: 1400,
      regenRate: 8349,
      power: 90,
      speed: 440,
      size: 100,
    },
    {
      id: "CD_NimbleBlaster",
      name: "Drek'ar",
      color: "#4760ff",
      cost: 10000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_NimbleMaster.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_NimbleBlaster.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_NimbleBlasher.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_NimbleBlaster.png",
      description: "",
      baseStagger: 1300,
      regenRate: 8349,
      power: 95,
      speed: 460,
      size: 100,
    },
    {
      id: "CD_StalwartProtector",
      name: "Dubu",
      color: "#ff9147",
      cost: 0,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_StalwartProtector.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_StalwartProtector.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_StalwartProtector.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_StalwartProtector.png",
      description: "",
      baseStagger: 1500,
      regenRate: 8349,
      power: 100,
      speed: 435,
      size: 100,
    },
    {
      id: "CD_EmpoweringEnchanter",
      name: "Era",
      color: "#c247ff",
      cost: 10000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_EmpoweringEnchanter.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_EmpoweringEnchanter.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_EmpoweringEnchanter.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_EmpoweringEnchanter.png",
      description: "",
      baseStagger: 1300,
      regenRate: 8349,
      power: 90,
      speed: 450,
      size: 100,
    },
    {
      id: "CD_TempoSniper",
      name: "Estelle",
      color: "#47d4ff",
      cost: 10000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_TempoSniper.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_TempoSniper.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_TempoSniper.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_TempoSniper.png",
      description: "",
      baseStagger: 1200,
      regenRate: 8349,
      power: 110,
      speed: 445,
      size: 100,
    },
    {
      id: "CD_GravityMage",
      name: "Finii",
      color: "#47c5ff",
      cost: 50000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_GravityMage.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_GravityMage.png",
      bodyShot: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_GravityMage.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_GravityMage.png",
      description: "",
      baseStagger: 1200,
      regenRate: 8349,
      power: 95,
      speed: 475,
      size: 100,
    },
    {
      id: "CD_FlexibleBrawler",
      name: "Juliette",
      color: "#ff5447",
      cost: 0,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_FlexibleBrawler.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_FlexibleBrawler.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_FlexibleBrawler.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_FlexibleBrawler.png",
      description: "",
      baseStagger: 1300,
      regenRate: 8349,
      power: 110,
      speed: 450,
      size: 100,
    },
    {
      id: "CD_CleverSummoner",
      name: "Juno",
      color: "#47ffd7",
      cost: 10000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_CleverSummoner.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_CleverSummoner.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_CleverSummoner.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_CleverSummoner.png",
      description: "",
      baseStagger: 1400,
      regenRate: 8349,
      power: 90,
      speed: 450,
      size: 100,
    },
    {
      id: "CD_SpeedySkirmisher",
      name: "Kai",
      color: "#ff47e3",
      cost: 0,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_SpeedySkirmisher.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_SpeedySkirmisher.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_SpeedySkirmisher.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_SpeedySkirmisher.png",
      description: "",
      baseStagger: 1150,
      regenRate: 8349,
      power: 90,
      speed: 475,
      size: 100,
    },
    {
      id: "CD_UmbrellaUser",
      name: "Kazan",
      color: "#ff6c47",
      cost: 50000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_UmbrellaUser_Default.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_UmbrellaUser.png",
      bodyShot: "/i/character/body/T_UI_FullCharacter_UmbrellaUser.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_UmbrellaUser.png",
      description: "",
      baseStagger: 1100,
      regenRate: 8349,
      power: 90,
      speed: 450,
      size: 100,
    },
    {
      id: "CD_ChaoticRocketeer",
      name: "Luna",
      color: "#edff47",
      cost: 30000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_ChaoticRocketeer.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_ChaoticRocketeer.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_ChaoticRocketeer.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_ChaoticRocketeer.png",
      description: "",
      baseStagger: 1200,
      regenRate: 8349,
      power: 110,
      speed: 460,
      size: 100,
    },
    {
      id: "CD_DrumOni",
      name: "Mako",
      color: "#ff478b",
      cost: 50000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_DrumOni_Default.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_DrumOni.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_DrumOni.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_DrumOni.png",
      description: "",
      baseStagger: 1300,
      regenRate: 8349,
      power: 110,
      speed: 440,
      size: 100,
    },
    {
      id: "CD_Healer",
      name: "Nao",
      color: "#9563c7",
      cost: 50000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_Healer_Default.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_Healer.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_Healer.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_Healer.png",
      description: "",
      baseStagger: 1100,
      regenRate: 8349,
      power: 90,
      speed: 455,
      size: 100,
    },
    {
      id: "CD_EDMOni",
      name: "Octavia",
      color: "#47fff0",
      cost: 50000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_AN_EDMOni.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_EDMOni.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_EDMOni.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_EDMOni.png",
      description: "",
      baseStagger: 1111,
      regenRate: 8349,
      power: 75,
      speed: 475,
      size: 100,
    },
    {
      id: "CD_WhipFighter",
      name: "Rasmus",
      color: "#51ffb8",
      cost: 50000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_WhipFighter.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_WhipFighter.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_WhipFighter.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_WhipFighter.png",
      description: "",
      baseStagger: 1300,
      regenRate: 0,
      power: 100,
      speed: 450,
      size: 100,
    },
    {
      id: "CD_ManipulatingMastermind",
      name: "Rune",
      color: "#8a47ff",
      cost: 30000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_ManipulatingMastermind.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_ManipulatingMastermind.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_ManipulatingMastermind.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_ManipulatingMastermind.png",
      description: "",
      baseStagger: 1300,
      regenRate: 8349,
      power: 100,
      speed: 460,
      size: 100,
    },
    {
      id: "CD_RockOni",
      name: "Vyce",
      color: "#ff8747",
      cost: 50000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_AN_RockOni.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_RockOni.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_RockOni.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_RockOni.png",
      description: "",
      baseStagger: 1200,
      regenRate: 8349,
      power: 110,
      speed: 450,
      size: 100,
    },
    {
      id: "CD_HulkingBeast",
      name: "X",
      color: "#eb3654",
      cost: 10000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_HulkingBeast.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_HulkingBeast.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_HulkingBeast.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_HulkingBeast.png",
      description: "",
      baseStagger: 1400,
      regenRate: 8349,
      power: 130,
      speed: 440,
      size: 100,
    },
    {
      id: "CD_FlashySwordsman",
      name: "Zentaro",
      color: "#c22727",
      cost: 50000,
      portrait: "/i/character/portrait/T_UI_Portrait_CloseUp_FlashySwordsman.png",
      goalScore: "/i/character/goalscore/T_UI_Portrait_GoalScore_FlashySwordsman.png",
      bodyShot: "/i/character/body/T_UI_Portrait_Concept_FlashySwordsman.png",
      timeline: "/i/character/timeline/T_UI_Portrait_CharacterSelect_Timeline_FlashySwordsman.png",
      description: "",
      baseStagger: 1100,
      regenRate: 8349,
      power: 100,
      speed: 460,
      size: 100,
    },
  ];

  for (const character of strikers) {
    await prisma.strikers.upsert({
      where: { id: character.id },
      update: {
        name: character.name,
        description: character.description,
        portrait: character.portrait,
        goalScore: character.goalScore,
        bodyShot: character.bodyShot,
        timeline: character.timeline,
      },
      create: {
        id: character.id,
        name: character.name,
        color: character.color,
        cost: character.cost,
        description: character.description,
        portrait: character.portrait,
        goalScore: character.goalScore,
        bodyShot: character.bodyShot,
        timeline: character.timeline,
        baseStagger: character.baseStagger,
        regenRate: character.regenRate,
        power: character.power,
        speed: character.speed,
        size: character.size
      },
    });
    console.log(chalk.gray(`[DEBUG] Upserted ${character.id} to Striker Table!`));
  }

  console.log(chalk.greenBright(`[>] Successfully added all strikers.`));
}


main().catch(console.error);